---
title: "R Notebook"
output: html_document
---

We'll need some libraries...

```{r,warning=FALSE,message=FALSE}

pacman::p_load(haven, purrr, knitr)

# I gave up, let's just use tidyverse for everything else
library(tidyverse)

```

### Question 1
#### 1a

Let us import the dataset and discover the necessary columns

```{r}

DISCRIM <- read_stata("http://fmwww.bc.edu/ec-p/data/wooldridge/discrim.dta")

Variables <- c(
  'pentree',
  'prpblck',
  'income',
  'lincome',
  'prppov',
  'lhseval'
)

# Text descriptions
Description <- unlist(Variables %>% map(function(row) attributes(DISCRIM[[row]])$label))

# Descriptive stats
fMapData <- function(F) {
  return (
        Variables
          %>% map(function(row) F(Filter(function(x) !is.na(x), DISCRIM[[row]])))
          %>% unlist
          %>% format(scientific = FALSE)
  )
}

Mean <- fMapData(mean)
StandardDeviation <- fMapData(sd)

kable(data.frame(
  Description, Variables, Mean, StandardDeviation
))

```

Thus, we can conclude that these variables have quite large deviations

#### 1b


```{r}
my_data <- as_tibble(DISCRIM)
variables <- (my_data
  %>% select(pentree, prpblck, income, lincome, prppov, lhseval)
  %>% filter(!is.na(pentree) & !is.na(prpblck))) # Apparently two of these is enough

  cor(variables)

```

#### 2

